### ISSUE TITLE
Verbandsabkürzungen in Großbuchstaben

### ISSUE THREAD

**Issue by jupadin** [djbrown/hbscorez#117]
Hi @djbrown,

wie findest Du die Idee, die Abkürzungen des jeweiligen Verbands als Großbuchstaben darzustellen ?

https://github.com/djbrown/hbscorez/blob/013af775f3e1964d542c456944a4067854f1424c/src/base/parsing.py#L28-L29

Mit entsprechender Anpassung des folgenden Tests

https://github.com/djbrown/hbscorez/blob/013af775f3e1964d542c456944a4067854f1424c/src/base/tests/unit/test_parsing.py#L39-L45

Ggfs. würde ich hier noch eine Anpassung des Funktionsnamens zu `test_parse_association_abbreviation` vorschlagen. Wie siehst Du das ?

Viele Grüße

**Comment by djbrown** [comment]
@jupadin danke für den Hinweis!
Verbandsabkürzungen sind jetzt in Großbuchstaben
Testmethodename habe ich belassen, da der Kontext über Modul- und Testklasse gegeben ist
