### ISSUE TITLE
Problem with missing report folder

### ISSUE THREAD

**Issue by airmax93** [djbrown/hbscorez#2]
Hey, 
i have some problems with the import_scores.py file. The script will crash if the report folder is missing at line 91.
I solve the problem by adding the following line of code above.
`        os.makedirs(os.path.dirname(game.report_path()), exist_ok=True)
`

**Comment by djbrown** [comment]
Hello @airmax93,

thanks for the improvement! :ok_hand:
I added your solution with commit 2bf7dd5e80801af1a5b7b85014a8d7a07d92f98d 

https://github.com/djbrown/hbscorez/blob/2bf7dd5e80801af1a5b7b85014a8d7a07d92f98d/base/management/commands/import_scores.py#L35
